### ISSUE TITLE
Not able to see tree view or graph view in Climate DT VM

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-gui#109]
In GitLab by @mcastril on Jun 3, 2024, 18:09

Hi @LuiggiTenorioK 

In the experiment [a0uq](https://climatedt-wf.csc.fi/experiment/a0uq/tree), I could not see the `tree view` or the `graph view`. This is the error message:

![Screenshot_from_2024-06-03_18-06-05](https://earth.bsc.es/gitlab/es/autosubmit-gui/uploads/15d32cd5fc781047e6eb8d3e60bef1bf/Screenshot_from_2024-06-03_18-06-05.png)

I confirm that I can visualize correctly other experiments with wrappers, such as [a0w1](https://climatedt-wf.csc.fi/experiment/a0w1/graph)

**Comment by LuiggiTenorioK** [comment]
Giving a look at the experiment [a0uq](https://climatedt-wf.csc.fi/experiment/a0uq/tree), I realized there is a missing `WRAPPERS` section in the yml config. I think it is possible that, in these experiments, someone has deleted that section after creating the workflow.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Jun 4, 2024, 09:19

But, as far as I know, the WRAPPERS section isn't mandatory, is it?

**Comment by LuiggiTenorioK** [comment]
In this case, it is mandatory because there were wrappers when the workflow was created. So, the API is trying to get the info related to it from the config files and it fails.

Still, I think this should not limit the API to return the tree, but this particular error is raised from the config parser and not from the API.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Jun 4, 2024, 09:33

I see. However, the user could have decided to remove the wrappers at any moment (or do you mean that they did it without stopping and doing autosubmit run)

CC @dbeltrankyl

**Comment by LuiggiTenorioK** [comment]
> I see. However, the user could have decided to remove the wrappers at any moment (or do you mean that they did it without stopping and doing autosubmit run)

At any moment. I think wrappers are defined when user do `autosubmit create`. So, the hypothetical sequence that led this experiment to this error might be:

1. User run `autosubmit create` with a `WRAPPERS` section in the conf
2. Wrappers are defined and stored in the DDBB
3. User deletes `WRAPPERS` section
4. API knows there are wrappers because of the DDBB and tries to get extra info from the yml files
5. This error arises

Still, not sure this is 100% right.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Jun 4, 2024, 10:27

 > At any moment. I think wrappers are defined when user do `autosubmit create`.

No, they're defined during running time. 

What `autosubmit create `is to fill an alternative table that "previews" how the wrapper will look. However, it could not be the final result because the preview is not emulating the time metric.

> 1. User deletes `WRAPPERS` section

There are some issues with this in Autosubmit itself, so maybe it is a similar issue

you can check https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1298 https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1292

Should be fixed in 4.1.7, the job_packages db sometimes it was not being reset ( per example, when the wrapper section ceases to exist)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Jun 4, 2024, 10:34

Thanks for the answers. I didn't know about that issue, I just read the conversations.

As @dbeltrankyl says, users should have the freedom to activate or deactive wrappers, even removing the section.

When do you intend to do the release Dani?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Jun 4, 2024, 10:39

This week

**Comment by LuiggiTenorioK** [comment]
mentioned in merge request ces/autosubmit4-config-parser!6

**Comment by LuiggiTenorioK** [comment]
Sent a MR to the config parser repo (https://earth.bsc.es/gitlab/ces/autosubmit4-config-parser/-/merge_requests/6). Already tested this experiment with these changes and it works.

Once this config parser change is released, we just need to update the parser without needing to update the API version and it will work.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Jun 7, 2024, 10:31

@dbeltrankyl will it still be ready this week?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Jun 7, 2024, 11:06

I've upload the autosubmit config version

**Comment by LuiggiTenorioK** [comment]
Got a new error that affected all the experiments when using the latest version of the parser (1.0.64)

```
Traceback (most recent call last):
  File "/appl/soft/4.0.0b8/lib64/python3.9/site-packages/autosubmit_api-4.0.0b8-py3.9.egg/autosubmit_api/experiment/common_requests.py", line 767, in get_experiment_tree_structured
    as_conf.reload(True)
  File "/appl/soft/4.0.0b8/lib64/python3.9/site-packages/autosubmitconfigparser/config/configcommon.py", line 1485, in reload
    custom_conf_pre = self.load_custom_config_section({}, filenames_to_load["PRE"])
  File "/appl/soft/4.0.0b8/lib64/python3.9/site-packages/autosubmitconfigparser/config/configcommon.py", line 1427, in load_custom_config_section
    current_data_pre, current_data_post = self.load_custom_config(current_data, filenames_to_load)
  File "/appl/soft/4.0.0b8/lib64/python3.9/site-packages/autosubmitconfigparser/config/configcommon.py", line 1381, in load_custom_config
    current_data_pre, current_data_post = self.load_config_folder(copy.deepcopy(current_data), filename)
  File "/appl/soft/4.0.0b8/lib64/python3.9/site-packages/autosubmitconfigparser/config/configcommon.py", line 644, in load_config_folder
    return self.load_custom_config(current_data, filenames_to_load)
  File "/appl/soft/4.0.0b8/lib64/python3.9/site-packages/autosubmitconfigparser/config/configcommon.py", line 1388, in load_custom_config
    self.load_config_file(current_data, filename)))
  File "/appl/soft/4.0.0b8/lib64/python3.9/site-packages/autosubmitconfigparser/config/configcommon.py", line 614, in load_config_file
    return self.unify_conf(current_folder_data, new_file.data)
  File "/appl/soft/4.0.0b8/lib64/python3.9/site-packages/autosubmitconfigparser/config/configcommon.py", line 692, in unify_conf
    self.dynamic_variables = list(set(self.dynamic_variables))
TypeError: unhashable type: 'list'

```

**Comment by LuiggiTenorioK** [comment]
@mcastril experiment `a0uq` is now visible with the API on port 8081 (via SSH) using the latest version of the config parser ([1.0.65](https://pypi.org/project/autosubmitconfigparser/1.0.65/)). Thanks @dbeltrankyl :raised_hands: 

I'll notify Henrik to upgrade that dependency of his API to this version.

**Comment by LuiggiTenorioK** [comment]
mentioned in issue digital-twins/de_340-2/project_management#334
