### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-gui#5]
In GitLab by @mcastril on Mar 14, 2022, 19:00

We will write down here the aspects that we see that need action or documentation:

Actions
- [x] Move the Autosubmit API project to CES
- [x] Remove AutosubmitAPI3 project?

Documentation
- [x] Unify or divide (make coherent) the [README](https://earth.bsc.es/gitlab/es/autosubmitreact/-/blob/master/README.md) and [Wiki](https://earth.bsc.es/gitlab/es/autosubmitreact/-/wikis/home)
- [x] Move API requests wiki to AutosubmitAPI (remove on AutosubmitGUI)?
- [x] AutosubmitGUI project structure documentation
- [x] AutosubmitAPI project structure documentation

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Mar 15, 2022, 13:13

@dbeltrankyl

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Mar 15, 2022, 15:36

@ jberlin will start testing the standalone installation as explained in the README

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Mar 16, 2022, 11:56

Hi 
a few initial comments based on the install instructions in the README:

- repository should be under a CES project and not an user `git clone https://earth.bsc.es/gitlab/wuruchi/autosubmitreact/`

- when I tried to clone, it redirects to another one but the result is only the readme to be downloaded.

ll autosubmitreact/
total 16
drwxrwxr-x  3 jberlin jberlin 4096 Mar 16 11:51 ./
drwxrwxr-x 11 jberlin jberlin 4096 Mar 16 11:51 ../
drwxrwxr-x  8 jberlin jberlin 4096 Mar 16 11:51 .git/
-rw-rw-r--  1 jberlin jberlin 2069 Mar 16 11:51 README.md

Maybe I am missing something @wuruchi ? thanks!

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Mar 16, 2022, 12:18

maybe the right git repo is this one:

https://earth.bsc.es/gitlab/es/autosubmitreact

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 16, 2022, 12:30

marked the checklist item **Remove AutosubmitAPI3 project?** as completed

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 16, 2022, 12:35

marked the checklist item **Move API requests wiki to AutosubmitAPI (remove on AutosubmitGUI)?** as completed

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 16, 2022, 13:04

Hello @ jberlin 

You are right, I need to update some data in the README and also fix some tests that became outdated. I'll work on it today. I'll post it here once it's done.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Mar 16, 2022, 13:06

Yes, that's the last one is the right one. The one in Wilmer's profile is the public one, only for advertisement and paper reproducibility purposes.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Mar 16, 2022, 15:29

Also when the npm part can begin (once the sources have been cloned), you should add a step to cd the project folder first so the json file can be loaded:

```
cd autosubmitreact
npm install
```
I having some issues but I guess is because I am using a old version of npm:

```
npm ERR! Linux 5.4.0-92-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm WARN deprecated vis@4.21.0: Please consider using https://github.com/visjs
WARN engine react-scripts@4.0.3: wanted: {"node":"^10.12.0 || >=12.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"})

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jberlin/Development/autosubmitreact/npm-debug.log

```

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Mar 16, 2022, 18:02

Hi 
I finally managed to get it installed and working. some remarks:

maybe adding a section for troubleshooting things/issues that can arise:

```
jberlin@bsces105017:~/Development$ npm -v
8.5.4
jberlin@bsces105017:~/Development$ cd autosubmitreact/
jberlin@bsces105017:~/Development/autosubmitreact$ npm install
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /home/jberlin/Development/autosubmitreact/node_modules/abab
npm ERR! dest /home/jberlin/Development/autosubmitreact/node_modules/.abab-WaUjw8uZ
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/home/jberlin/Development/autosubmitreact/node_modules/abab' -> '/home/jberlin/Development/autosubmitreact/node_modules/.abab-WaUjw8uZ'
npm ERR!  [Error: EACCES: permission denied, rename '/home/jberlin/Development/autosubmitreact/node_modules/abab' -> '/home/jberlin/Development/autosubmitreact/node_modules/.abab-WaUjw8uZ'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/home/jberlin/Development/autosubmitreact/node_modules/abab',
npm ERR!   dest: '/home/jberlin/Development/autosubmitreact/node_modules/.abab-WaUjw8uZ'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jberlin/.npm/_logs/2022-03-16T16_13_39_286Z-debug-0.log
```

I removed the node_modules from the directory with all its  content and it made the trick

Then when I tried to run it:


```
/home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/chokidar.js:17
throw new Error(
^

Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'
Require stack:
- /home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/chokidar.js
- /home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/DirectoryWatcher.js
- /home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/watcherManager.js
- /home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/watchpack.js
- /home/jberlin/Development/autosubmitreact/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /home/jberlin/Development/autosubmitreact/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /home/jberlin/Development/autosubmitreact/node_modules/webpack/lib/webpack.js
- /home/jberlin/Development/autosubmitreact/node_modules/react-scripts/scripts/start.js
chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
Require stack:
- /home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/chokidar.js
- /home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/DirectoryWatcher.js
- /home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/watcherManager.js
- /home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/watchpack.js
- /home/jberlin/Development/autosubmitreact/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /home/jberlin/Development/autosubmitreact/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /home/jberlin/Development/autosubmitreact/node_modules/webpack/lib/webpack.js
- /home/jberlin/Development/autosubmitreact/node_modules/react-scripts/scripts/start.js

    at Object.<anonymous> (/home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/chokidar.js:17:7)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/jberlin/Development/autosubmitreact/node_modules/watchpack/lib/DirectoryWatcher.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
```

The solution was to install the chokidar package as pointed out in the error:

 `npm install chokidar`

after all this I got it up and run

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Mar 16, 2022, 18:06

Thanks @ jberlin. This will be helpful and as you say they would be indicated as notes in the installation instructions.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 16, 2022, 19:02

Hello @ jberlin 

Thanks for the testing. I have updated the tests according to the latest changes. I've also updated the README with more instructions but I haven't considered your latest comments yet. I'll add further instructions, as suggested, in the next commit.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Mar 18, 2022, 17:19

Hi @wuruchi,

I noticed that even if it is deployed locally, the GUI app always redirects to `https://earth.bsc.es/autosubmitapp/`, there is any way to dissable SSO login when `NOAPI = true;` and use the local url ? I tried setting `authentication = false` but it did not work (I restarted the npm server to check that).

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 18, 2022, 18:12

Hello @ jberlin 

I just performed a fresh install of `autosubmitreact`, and after setting:

`export const AUTHENTICATION = false;`

I am not redirected to the SSO page. Can you stop the server and verify that all your files (in the IDE) are properly saved and then perform `npm start` again?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 25, 2022, 11:09

marked the checklist item **Move the Autosubmit API project to CES** as completed

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 25, 2022, 11:10

marked the checklist item **Unify or divide (make coherent) the [README](https://earth.bsc.es/gitlab/es/autosubmitreact/-/blob/master/README.md) and [Wiki](https://earth.bsc.es/gitlab/es/autosubmitreact/-/wikis/home)** as completed

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 25, 2022, 11:10

Hello @mcastril 

I have updated the main [README](https://earth.bsc.es/gitlab/es/autosubmitreact) file. It now includes the description from the wiki. I have deleted the wiki page.

I have also updated the main [README](https://earth.bsc.es/gitlab/es/autosubmit_api) file of the `Autosubmit API` project.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Mar 25, 2022, 18:14

Thanks @wuruchi, now it's better organized.

I have a doubt, what button does this `RUNNING` button refer to?

> Press the green **RUNNING** button, if it does not return anything, try entering the name of an experiment you know exists in the search textbox and press SEARCH. If even then there are no results, then it is most likely that there is some problem with the API.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 25, 2022, 18:26

Oh, it was supposed to be `ACTIVE EXPS`, it used to be called `RUNNING`. I'll fix it.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Mar 28, 2022, 11:42

Hi @wuruchi , 

Please if possible , would be great to have a small troubleshooting section for the most common issues/problems:

- The app is down, how do you proceed to address the problem ? which server logs you look at ? you contact operations ? or you log in the web server ? 
- How the upgrades of the app are usually carried out ? you update without disruptiong the server (hot upgrade) ? or you stop it , install the new version and restart it (cold upgrade) ? 
- Which logs you usually check to detect issues ?

This is not user guide stuff, is more related to how to keep running the app properly for the maintainers.

Thanks!!

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 28, 2022, 12:54

Hello @ jberlin 

Sure, I'll work on it.

@mcastril Do you think we should add this information as part of the `README` file or as a `Wiki` page?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Mar 28, 2022, 19:24

Hi,

You are right @ jberlin, that the current README only covers the recovery of the service. That information that you ask is needed.

I would add it to the wiki, because it's less general information.

Maybe you can move also the "Deployment" part there since it's not generic and refers to servers and links from the BSC installation.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Mar 28, 2022, 19:26

After adding this information, the right test I think would be that @ jberlin performs an update under the supervision of @wuruchi to check that the documentation is fine.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Mar 30, 2022, 13:18

Hello @mcastril 

> After adding this information, the right test I think would be that @ jberlin performs an update under the supervision of @wuruchi to check that the documentation is fine.

Sure, that would be no problem.

According to your suggestions, I've updated the wiki documentation of Autosubmit API:

https://earth.bsc.es/gitlab/es/autosubmit_api/-/wikis/home

And Autosubmit GUI:

https://earth.bsc.es/gitlab/es/autosubmitreact/-/wikis/home

FYI @ jberlin

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 1, 2022, 18:05

Hi @wuruchi ,

I made a high level sequence diagram to understand better the flow of events in the app, if you have some time please have a look , it can also useful to add to the main documentation where the structure of the project will be documented:

https://drive.google.com/file/d/1SgNsSfKQYFIyxNTG7msQqJaHMgkm1kZt/view?usp=sharing

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 4, 2022, 16:27

Hi @wuruchi , I re-checked the readme, there is a section called deployment (item nr 6) but in the text actually it doesnt exist. the deployment section should cover the needed steps at bsc infraestructure to properly run the application and the troubleshooting of any arising issue on performing the deploy, this can be what should we tell support or operations in order to have a webserver ready to properly deploy the application. since is very uncommon to have admin rights in these machines unless is one as we asked to perform the installation.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 5, 2022, 10:29

Bravo @ jberlin . For any reason I can only see a low-res version. Would it be possible to increase the fig size?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 5, 2022, 16:58

Hi @wuruchi , I was checking the [documentation](https://earth.bsc.es/gitlab/es/autosubmit_api/-/wikis/Deployment-and-Update) concerned the Autosubmit API installation, I am looking at this page:

Some details are missed such as:
- base software needed to properly deploy the Autosubmit API
- where to clone the master branch
- maybe some links on how to deploy [gunicorn](https://gunicorn.org/#deployment)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 7, 2022, 10:13

@wuruchi could you add the dependencies of the API and how to install them?

Also, in the deployment section, it is not clear where the `autosubmit_api` is deployed, can you add this step too?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 7, 2022, 10:41

Also comment about the .autosubmitrc file

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 8, 2022, 09:29

Thanks for updating the instructions @wuruchi. I only miss the `gunicorn`. Do you deploy it also in the `venv` ?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 8, 2022, 15:56

marked the checklist item **AutosubmitGUI project structure documentation** as completed

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 8, 2022, 15:58

@wuruchi can you add similar README.md files in the API structure ?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 8, 2022, 15:59

And last item: how the workers are configured and managed? Do they need any special treatment? How they are triggered?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Apr 11, 2022, 11:54

Sure.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Apr 11, 2022, 11:56

All the workers are triggered through the crontab. Here is the current configuration in `bscesweb04`:

```
*/3 * * * * /srv/www/htdocs/AutosubmitAPI/venv27/bin/python -W ignore /srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/populate_queue_run_times.py
*/5 * * * * /srv/www/htdocs/AutosubmitAPI/venv27/bin/python -W ignore /srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/populate_running_experiments.py
0 */13 * * * /srv/www/htdocs/AutosubmitAPI/venv27/bin/python -W ignore /srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/populate_graph.py
*/10 * * * * /srv/www/htdocs/AutosubmitAPI/venv27/bin/python -W ignore /srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/verify_complete.py
*/10 * * * * /srv/www/htdocs/AutosubmitAPI/venv27/bin/python -W ignore /srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/test_esarchive.py
0 */4 * * * /srv/www/htdocs/AutosubmitAPI/venv27/bin/python -W ignore /srv/www/htdocs/AutosubmitAPI/venv27/lib/python2.7/site-packages/autosubmit_api/workers/populate_details_db.py
@ reboot /home/webadmin/run_gunicorn.sh
```

I will reproduce this information in a wiki page.

Added: https://earth.bsc.es/gitlab/es/autosubmit_api/-/wikis/home

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 11, 2022, 12:33

Hi @wuruchi ,
Step 4 of API deployment I think it can be improved:

> To start `gunicorn` for `autosubmit_api` execute: `gunicorn --error-logfile ~/logunicorn0320.txt --timeout 600 -b 0.0.0.0:8081 -w 4 autosubmit_api.app:app --daemon`, where `~/logunicorn0320.txt` is the path to the **log file** that will be used (it does not need to exist beforehand), `--timeout 600` indicates the number of seconds that `gunicorn` will wait for each process before killing it, `-b 0.0.0.0:8081` is the IP and port that will be used (two services cannot share the same IP and port, `0.0.0.0` is a shortcut for localhost, in production, the public address will be `http://192.168.11.91:8081` if running on `bscesweb04`), `autosubmit_api.app:app` is the name of the file that exposes the operations that the API will answer, and `--daemon` is a flag that indicates that this is a background process.

if you want an user to execute a given command, put in separate box so is not mixed with the text, if you want to provide an overview of each parameter, please put a bullet list or table below the command, so this will improve readability

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Apr 13, 2022, 12:13

Hello @ jberlin 

I took a look at the diagram and it is correct.

`useEffect()` might give you some problems in the future. Keep in mind that the code inside its arrow function will be executed every time the component is rendered (or re-rendered), so if there is some code inside it that also modifies the current state of the app, it might result in an infinite loop that crashes the app. In order to avoid it, you need to carefully place restrictions (conditionals) inside the arrow function.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Apr 14, 2022, 12:48

marked the checklist item **AutosubmitAPI project structure documentation** as completed
